### ISSUE TITLE
Error when opening tokenizer interface

### ISSUE THREAD

**Issue by laurieathey** [MrPrimate/vtta-tokenizer#15]
After the fix for number #6 we now get a new error

![image](https://user-images.githubusercontent.com/11553364/109398397-122f7c80-793d-11eb-8b51-d62efc459a60.png)
Just comes up with that in the console but two errors pop up in-game
![image](https://user-images.githubusercontent.com/11553364/109398413-25dae300-793d-11eb-90e0-720d31edf5be.png)
and the interface looks like this
![image](https://user-images.githubusercontent.com/11553364/109398432-38edb300-793d-11eb-91cc-c148e2cab1ae.png)
until shortly after the error appears the second empty window doesn't exist at all and the UI looks a bit F-ed.
It corrects itself to what you can see in the screenshot once it's had the error.

As you can see it doesn't add the frame layer or the mystery-man image.

I can recover from this by adding an image and finding the frame image.

**Comment by Bosies** [comment]
I have this issue as well where I can't place a portrait for an enemy character, claiming my picture is not of a correct format and that the location where the file is "null" (but it exists).

**Comment by MrPrimate** [comment]
I'm struggling to replicate this - what is your Avatar/Token upload directory set to? Does this happen on new actors, or is it for existing ones? NPC's/Characters/both? From the scene or from the actors tab?

**Comment by laurieathey** [comment]
Ok, I'm in the latest of the pathfinder 2e system.
Foundry 0.7.9
Fairly sure I'm on latest of your mod, I re-downloaded it when you responded about fixing it.

NPC Sheets
I just tried it and replicated the above with actors (Let's call this one Crystal Patch) I've used for games a few weeks ago, so not "new" actors, though I hadn't done anything special with their images since these were for traps.

Tried it with one from AGES ago that did have an image for the token but just mystery man for the artwork. That still threw the "can't find mystery man" error.

tried putting Crystal Patch on a map and opening the token's sheet and editing it, same behaviour. Doesn't seem to matter where I open it.

PC Sheets
No errors at all if it's a PC sheet.

Settings
![image](https://user-images.githubusercontent.com/11553364/109414341-ae479b00-79b2-11eb-9229-876aafc0fa86.png)

I've not changed those since installing it again. It might have kept some changes from before? I don't know if mods lose all custom settings from before or if they're cached somewhere and picked back up when you re-install.

**Comment by MrPrimate** [comment]
It looks like your on The Forge - can you try selecting an upload directory in your "My Assets Library" it should then look something like: `[forgevtt] tokens`

**Comment by laurieathey** [comment]
That was already working with just `/tokens` but I used the file browser to point it at that folder again, it now says `[forgevtt] tokens` 

I did notice though that the mystery man image (Which I've have never personally set up) was not there. Like that file's location does not exist.

I checked that by going into the prototype token and looking at the image path. if I try to look for that image I see this:
![image](https://user-images.githubusercontent.com/11553364/109415379-9e32ba00-79b8-11eb-9bbe-4cb147cf80fe.png)

It actually says "No matching results found in this location". I have no idea what happened honestly but that's likely what is causing the error. The location you can see in the image is not one I EVER touch. I'm not even sure if I can change/add/remove files in that directory. As far as I'm aware that's the default image used.

**Comment by MrPrimate** [comment]
And just to confirm this is version 2.2.6 of Tokenizer?

**Comment by laurieathey** [comment]
Yep. Just checked, 2.2.6
![image](https://user-images.githubusercontent.com/11553364/109423149-b5849e00-79de-11eb-84b6-511cbdb7bb40.png)

**Comment by rrenna** [comment]
Looks like after I updated the upload directory reset to `null` for me, this was causing similar issues with my setup.

![2021-03-01 at 11 24 AM](https://user-images.githubusercontent.com/849462/109526647-cdacf980-7a80-11eb-93fa-f5bcccab1267.png)

**Comment by laquasicinque** [comment]
I found the cause, the next PR should fix it the null issue from occuring and clean it up

**Comment by laurieathey** [comment]
![image](https://user-images.githubusercontent.com/11553364/109637380-00242880-7b4d-11eb-9697-cdbb31cbcfbb.png)

Guessing the PR didn't fix it after all?

**Comment by laurieathey** [comment]
Shit, that button didn't do what I thought it was gonna do lol

**Comment by MrPrimate** [comment]
![image](https://media1.giphy.com/media/Yl5aO3gdVfsQ0/giphy.gif)

**Comment by laquasicinque** [comment]
The question is though, has it fixed it for your issues @laurieathey  @rrenna  and @Bosies

**Comment by laurieathey** [comment]
Still no update for it on the Forge, I'll check again tonight and see if the update has reached us :)

**Comment by laurieathey** [comment]
Sorry, I checked for like a day then forgot 😆 
I've got the update. So it now throws the errors in game, but recovers and sets the token layers correctly.
Bit of a delay in it happening though, dunno if that bothers you or not. 
It does mean I just need wait ~5 seconds and my token is ready for the usual editing though so I'll take it :)

**Comment by laquasicinque** [comment]
The only part I could think of that could make it take that long would be loading times as it tries to load a few pictures

**Comment by laurieathey** [comment]
I'm not sure. It's not breaking it though, and it takes less than time it takes me to navigate to the image of the frame every time so I'm happy with it :)
